"""Add advanced privacy and family controls

Revision ID: f08ca6afa2af
Revises: cddcce27c808
Create Date: 2026-10-01 07:49:27.124056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08ca6afa2af'
down_revision: Union[str, None] = 'cddcce27c808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_privacy_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('allow_member_discovery', sa.Boolean(), nullable=False),
    sa.Column('default_content_visibility', sa.String(), nullable=False),
    sa.Column('member_invites_role', sa.String(), nullable=False),
    sa.Column('member_management_role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id')
    )
    op.create_table('album_allowed_users',
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'user_id')
    )
    op.create_table('memory_allowed_users',
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id', 'user_id')
    )
    op.add_column('albums', sa.Column('visibility', sa.String(), nullable=False))
    op.add_column('memories', sa.Column('visibility', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'visibility')
    op.drop_column('albums', 'visibility')
    op.drop_table('memory_allowed_users')
    op.drop_table('album_allowed_users')
    op.drop_table('family_privacy_settings')
    # ### end Alembic commands ###
