"""add invitation_type to invitations

Revision ID: 5dd9cf70409d
Revises: 001_initial_schema
Create Date: 2026-09-30 13:11:50.690870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd9cf70409d'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('invitation_type', sa.String(length=50), server_default='person_claim', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'invitation_type')
    # ### end Alembic commands ###
