"""Add privacy settings

Revision ID: 459735fd8c48
Revises: ee2e40e8a8fe
Create Date: 2026-10-01 04:29:31.135418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459735fd8c48'
down_revision: Union[str, None] = 'ee2e40e8a8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_privacy_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('phone_visibility', sa.String(), nullable=False),
    sa.Column('email_visibility', sa.String(), nullable=False),
    sa.Column('dob_visibility', sa.String(), nullable=False),
    sa.Column('bio_visibility', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_privacy_settings')
    # ### end Alembic commands ###
