"""add_employment_and_notification_events

Revision ID: 04ff8bac481c
Revises: f08ca6afa2af
Create Date: 2026-10-01 10:10:18.995978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ff8bac481c'
down_revision: Union[str, None] = 'f08ca6afa2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employments_person_id'), 'employments', ['person_id'], unique=False)
    op.add_column('notification_preferences', sa.Column('birthdays_enabled', sa.Boolean(), nullable=False))
    op.add_column('notification_preferences', sa.Column('anniversaries_enabled', sa.Boolean(), nullable=False))
    op.add_column('notification_preferences', sa.Column('remembrance_enabled', sa.Boolean(), nullable=False))
    op.add_column('notification_preferences', sa.Column('work_anniversaries_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'work_anniversaries_enabled')
    op.drop_column('notification_preferences', 'remembrance_enabled')
    op.drop_column('notification_preferences', 'anniversaries_enabled')
    op.drop_column('notification_preferences', 'birthdays_enabled')
    op.drop_index(op.f('ix_employments_person_id'), table_name='employments')
    op.drop_table('employments')
    # ### end Alembic commands ###
